name: Update resource pack

on:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Update language files
        run: |
          git submodule sync
          git submodule update --remote --recursive --force

      - name: Update resource pack
        run: |
          uv run mapping.py
          uv run pack.py

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update language files"

      - name: Get Minecraft version
        run: |
          cd mc_lang
          cat version.txt
          echo "ver=$(<version.txt)" >> "$GITHUB_ENV"

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ env.ver }}
          files: |
            output/1.7.10/renovation_translation_pack_1.7.10.zip
            output/1.8.9/renovation_translation_pack_1.8.9.zip
            output/1.9.4/renovation_translation_pack_1.9.4.zip
            output/1.10.2/renovation_translation_pack_1.10.2.zip
            output/1.11.2/renovation_translation_pack_1.11.2.zip
            output/1.12.2/renovation_translation_pack_1.12.2.zip
            output/1.13.2/renovation_translation_pack_1.13.2.zip
            output/1.14.4/renovation_translation_pack_1.14.4.zip
            output/1.15.2/renovation_translation_pack_1.15.2.zip
            output/1.16.5/renovation_translation_pack_1.16.5.zip
            output/1.17.1/renovation_translation_pack_1.17.1.zip
            output/1.18.2/renovation_translation_pack_1.18.2.zip
            output/1.19.2/renovation_translation_pack_1.19.2.zip
          name: ${{ env.ver }}
          version: ${{ env.ver }}
